export const EMAIL_SERVICE_ENDPOINT = 'PASTE_YOUR_FUNCTION_URL_HERE';
export const UKVD_API_KEY = 'YOUR_UKVD_API_KEY_HERE';
export const ROBOFLOW_API_URL = 'YOUR_ROBOFLOW_MODEL_URL_HERE';
export const ROBOFLOW_API_KEY = 'YOUR_ROBOFLOW_API_KEY_HERE';
